name: Build and Release

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Framework
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0'

      - name: Restore NuGet packages
        run: nuget restore

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Build the project
        run: msbuild.exe /t:restore /t:build /p:Configuration=Release

      - name: Zip app binaries
        run: |
          $sourceDir = "./bin/Release"
          mkdir ./bin/zip
          $destFile = "./bin/zip"
          Add-Type -AssemblyName System.IO.Compression.FileSystem
          [System.IO.Compression.ZipFile]::CreateFromDirectory($sourceDir, $destFile)

      - name: Create release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false

      - name: Upload release assets
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/zip/app.zip
          asset_name: app.zip
          asset_content_type: application/zip

      - name: Publish artifacts
        uses: actions/upload-artifact@v2.2.0
        with:
          name: app
          path: ./bin/zip/
